# Generated by Django 5.1.4 on 2025-01-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosEnviados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_sig', models.IntegerField()),
                ('tipo_documento', models.CharField(max_length=20)),
                ('numero_documento', models.CharField(max_length=20)),
                ('numero_telefono', models.CharField(max_length=15)),
                ('operadora', models.CharField(max_length=50)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('enviado_bot', models.BooleanField(default=False)),
                ('respuesta_bot', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
    ]
